basePath: /api/v1
info:
  contact: {}
  description: gin 框架示例
  title: gin example
  version: v0.0.1
paths:
  /public/user/login/{user}:
    post:
      consumes:
      - application/json
      description: 传入用户名,密码进行登录操作
      parameters:
      - description: 用户名
        in: path
        name: user
        required: true
        type: string
      responses:
        "200":
          description: 登录成功
          schema:
            type: ""
        "400":
          description: 登录失败
          schema:
            type: ""
      summary: 用户登录接口
      tags:
      - USER
swagger: "2.0"
